### ISSUE TITLE
breaking the Docker docs.

### ISSUE THREAD

**Issue by SvenDowideit** [cruxlinux/docker-crux#1]
duude!

you're breaking the docs...

```

There is a CRUX image maintained by [James Mills](http://prologic.shortcircuit.net.au/)
as part of the Docker "Official Library" of images. To use this image simply pull it
or use it as part of your `FROM` line in your `Dockerfile(s)`.
```

and nope - that site is soooo dead.

**Comment by SvenDowideit** [comment]
I've raised https://github.com/docker-library/docs/issues/661

**Comment by prologic** [comment]
*sigh* I'm not even maintaining this anymore :/


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by lag-linaro** [comment]
This is all about to change.

Prepare for the resurgence.
